version: '2.19.0'

volumes:
  db-data:
    driver: local

services:
  app:
    build:
      context: .
    container_name: CleverBank
    restart: always
    ports:
      - '8080:8080'
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/clever_bank
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=87654321

  db:
    image: postgres:15.1-alpine
    container_name: postgresDB
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=87654321
      - POSTGRES_DB=clever_bank
    ports:
      - "5432:5432"

    volumes:
      - db-data:/var/lib/postgresql/data
